version: 2.1

jobs:
  test_plugin:
    machine: true
    steps:
      - checkout
      - background: true
        command: |
          docker compose up
      - run: sleep 10 # you 
      - run: curl -X GET localhost:80 

workflows:
  test:
    jobs:
      - test_plugin
